### ISSUE TITLE
tiktok.py:44 in get_data

### ISSUE THREAD

**Issue by panikajoreserv** [valsoray-dev/tiktok-telegram-bot#1]
41 │   │   │   URL, data={"aweme_ids": f"[{aweme_id}]"}, params=PARAMS, head │
                    │   42 │   │   ) as response:                                                    │
                    │   43 │   │   │   json = await response.json()                                  │
                    │ ❱ 44 │   │   │   if json["status_code"] != 0:                                  │
                    │   45 │   │   │   │   raise Exception(json["status_msg"])                       │
                    │   46 │   │   │   return json["aweme_details"][0]

**Comment by valsoray-dev** [comment]
If you wanted to point out a bug, you should have written a description of the issue.
